name: ci
on: [workflow_dispatch, push, pull_request]
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    # Workaround to resolve link error with C:\msys64\mingw64\bin\libclang.dll
    - name: Remove msys64
      if: runner.os == 'Windows'
      run: Remove-Item -LiteralPath "C:\msys64\" -Force -Recurse
    - name: Install Windows dependencies
      if: runner.os == 'windows-latest'
      run: choco install llvm -y
    - run: cargo test --all
